### ISSUE TITLE
Using ZettelSearch to only search note titles

### ISSUE THREAD

**Issue by joshuaberetta** [michal-h21/vim-zettel#95] opened 2021-01-17 11:58 UTC
Is it possible to modify the ZettelSearch command to only search note titles and not the contents of the notes too? Something along the lines of what Obsidian does when pressing `[[`.

**Comment by IIPatternII** [comment] 2021-01-28 13:43
I made my own remaps to accomplish just that. They worked just fine until I updated the vim-zettel version. Care to try them out to check if you can use them? They are at #98. Please, let me know if they work for you!

**Comment by joshuaberetta** [comment] 2021-01-28 18:59
Hi @IIPatternII, thanks for linking your solution — unfortunately it's not working for me either 😢 This is the main thing that's forcing me to stick with Obsidian for now.

**Comment by IIPatternII** [comment] 2021-01-28 19:20
@joshuaberetta ok! Thanks! At least you managed to reproduce the error, which is a step in the right direction! 

Sadly, I don't know VimScript, so I can't do much to solve the problem. Hopefully, someone will save us! 😅

**Comment by joshuaberetta** [comment] 2021-01-29 00:18
@IIPatternII, I'm also useless with VimScript. I tried making some small changes but just broke everything :joy:

**Comment by rattletat** [comment] 2021-02-09 14:43
@joshuaberetta Here is my solution using fzf: 
```
let g:zettel_fzf_command = "rg --column --line-number --color=always --smart-case --regexp '^title: (.+)' --replace '$1'"
let g:zettel_fzf_options = ['--with-nth=-1']
```

**Comment by joshuaberetta** [comment] 2021-02-09 17:34
@rattletat thanks! I tried your suggestion but it only seems to work for files in the current directory 😢

**Comment by rattletat** [comment] 2021-02-09 18:13
@joshuaberetta Since I have my files all in one folder, this is enough for me atleast. Do you want to search files that are in different directories? You can probably provide them to ripgrep in some way.

**Comment by joshuaberetta** [comment] 2021-02-09 18:28
@rattletat managed to get it working for me by adding `./*` to the end of your `rg` command 🥲

**Comment by IIPatternII** [comment] 2021-02-11 17:28
@joshuaberetta your solution works great! I also need to be able to search the entire file. Do you know a way choose between searching only the title or the entire file? See #98 for more info.

@rattletat  you should close the issue.

**Comment by rattletat** [comment] 2021-02-12 04:19
@joshuaberetta you should close it^^

@IIPatternII  You could just get the 'junegunn/fzf.vim' and bind the `:Rg` command yourself. You probably need to set the working directory. Using fzf (and ripgrep) you can configure everything as you want, since they are very powerful tools. It is really worthwhile to skim the manpages of ripgrep. 

For example, a vim function which would do the same thing as the issue above just using the `fzf.vim` plugin:
```vim
    function! ZettelSearchTitle ()
      let command = "rg --column --line-number --color=always --smart-case --regexp '^title: (.+)' --replace '$1' -- . " . expand("%:h")
      let spec = {'options': ['--delimiter=:', '--with-nth=-1']}
      call fzf#vim#grep(command, 1, fzf#vim#with_preview(spec), 0)
    endfunction
```

If you want to search all lines, you only need to remove the regex and replace part:

```vim
    function! ZettelSearchTitle ()
      let command = "rg --column --line-number --color=always --smart-case -- . " . expand("%:h")
      let spec = {'options': ['--delimiter=:', '--with-nth=-1']}
      call fzf#vim#grep(command, 1, fzf#vim#with_preview(spec), 0)
    endfunction
```

**Closed** 2021-02-12 17:18 UTC
